# Generated by Django 4.1.5 on 2023-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('destino', models.CharField(max_length=40, verbose_name='Destino')),
                ('cantidadPasajero', models.CharField(max_length=5000, verbose_name='CantidadPasajero')),
                ('distanciaRecorrer', models.CharField(max_length=1000000000, verbose_name='DistanciaRecorrer')),
            ],
        ),
    ]
