# Generated by Django 4.1.5 on 2023-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('edad', models.CharField(max_length=250, verbose_name='Edad')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo')),
            ],
        ),
    ]
